(() => {
'use strict';
const D=window.SB_DATA;
const canvas=document.getElementById('game'),ctx=canvas.getContext('2d');
const W=canvas.width,H=canvas.height,el=id=>document.getElementById(id);
const ui={hearts:el('hearts'),stage:el('stage'),stars:el('stars'),coins:el('coins'),time:el('time'),status:el('status'),overlay:el('overlay'),title:el('overlayTitle'),text:el('overlayText'),result:el('resultBox'),menu:el('mainMenu'),select:el('stageSelect'),mute:el('muteBtn'),restart:el('restartBtn'),controller:el('controllerStatus')};
const SAVE_KEY='skyboundSprintSaveV2';
const save=(()=>{try{return Object.assign({unlocked:1,best:{},stars:{},ghosts:{},ghostOn:true},JSON.parse(localStorage.getItem(SAVE_KEY)||'{}'));}catch{return {unlocked:1,best:{},stars:{},ghosts:{},ghostOn:true};}})();
const persist=()=>{try{localStorage.setItem(SAVE_KEY,JSON.stringify(save));}catch{}};
const art={};for(const [n,s] of Object.entries(D.assets)){const i=new Image();i.crossOrigin='anonymous';i.src=s;art[n]=i;}
const aud={};for(const [n,s] of Object.entries(D.audio)){const a=new Audio(s);a.preload='auto';a.crossOrigin='anonymous';a.volume=n==='bgm'?.2:.52;if(n==='bgm')a.loop=true;aud[n]=a;}
const SB=window.SB={canvas,ctx,W,H,ui,D,save,persist,art,aud};
SB.input={left:false,right:false,jump:false};SB.pad={left:false,right:false,jump:false,start:false,b:false,index:null};SB.muted=false;
SB.state='title';SB.currentStage=0;SB.world=null;SB.hearts=3;SB.elapsed=0;SB.stageStart=0;SB.cameraX=0;SB.cameraY=0;SB.last=performance.now();SB.deaths=0;SB.runDamage=false;SB.checkpoint=null;SB.ghostFrames=[];SB.ghostClock=0;SB.particles=[];SB.shake=0;SB.flash=0;
SB.player={x:0,y:0,w:46,h:68,vx:0,vy:0,face:1,onGround:false,coyote:0,jumpBuffer:0,wallGrace:0,wallDir:0,jumpHeld:false,dashUntil:0,wallLock:0,invuln:0,coins:0,stars:0,anim:0};
SB.prevDir=0;SB.tapDir=0;SB.tapTime=0;SB.prevJump=false;SB.prevPadStart=false;

SB.sfx=(n,v)=>{if(SB.muted||!aud[n])return;try{const a=aud[n].cloneNode();a.volume=v??aud[n].volume;a.play().catch(()=>{});}catch{}};
SB.bgm=on=>{const a=aud.bgm;if(!a)return;if(on&&!SB.muted)a.play().catch(()=>{});else a.pause();};
SB.cloneStage=i=>{const s=D.stages[i];return {...s,spawn:[...s.spawn],goal:[...s.goal],platforms:s.platforms.map(p=>({...p})),coins:s.coins.map(c=>({...c})),stars:s.stars.map(c=>({...c})),enemies:s.enemies.map(e=>({...e})),checkpoints:s.checkpoints.map(c=>({...c})),hazards:s.hazards.map(h=>({...h}))};};
SB.rankFor=(t,s)=>t<=s.rank[0]?'S':t<=s.rank[1]?'A':t<=s.rank[2]?'B':'C';
SB.resetPlayer=(x,y)=>{Object.assign(SB.player,{x,y,vx:0,vy:0,invuln:1,coyote:0,jumpBuffer:0,wallGrace:0,dashUntil:0,wallLock:0});};
SB.startStage=(i,{freshHearts=true}={})=>{SB.currentStage=i;SB.world=SB.cloneStage(i);if(freshHearts)SB.hearts=3;SB.deaths=0;SB.runDamage=false;SB.player.coins=0;SB.player.stars=0;SB.checkpoint={x:SB.world.spawn[0],y:SB.world.spawn[1]};SB.resetPlayer(SB.checkpoint.x,SB.checkpoint.y);SB.elapsed=0;SB.stageStart=performance.now();SB.ghostFrames=[];SB.ghostClock=0;SB.particles=[];SB.cameraX=0;SB.cameraY=SB.world.vertical?Math.max(0,SB.world.height-H):0;SB.state='play';ui.overlay.classList.add('hidden');ui.result.classList.add('hidden');SB.bgm(true);SB.syncHud();};
SB.respawn=()=>SB.resetPlayer(SB.checkpoint.x,SB.checkpoint.y);
SB.hurt=()=>{const p=SB.player;if(p.invuln>0||SB.state!=='play')return;SB.hearts--;SB.deaths++;SB.runDamage=true;SB.shake=12;SB.flash=.22;SB.sfx('damage');SB.burst(p.x+p.w/2,p.y+p.h/2,14,'#fff');if(navigator.vibrate)navigator.vibrate(35);if(SB.hearts<=0){SB.state='gameover';SB.bgm(false);SB.showGameOver();}else SB.respawn();SB.syncHud();};
SB.showGameOver=()=>{ui.overlay.classList.remove('hidden');ui.title.textContent='GAME OVER';ui.text.textContent='チェックポイントからすぐ再挑戦できます。';ui.result.classList.remove('hidden');ui.result.innerHTML=`<div>STAGE<br><b>${SB.currentStage+1}</b></div><div>DEATHS<br><b>${SB.deaths}</b></div>`;ui.menu.innerHTML='<button id="retryNow">RETRY CHECKPOINT</button><button id="titleNow" class="secondary">TITLE</button>';el('retryNow').onclick=()=>{SB.hearts=3;SB.state='play';ui.overlay.classList.add('hidden');SB.respawn();SB.stageStart=performance.now()-SB.elapsed*1000;SB.bgm(true);};el('titleNow').onclick=SB.showTitle;};
SB.finishStage=()=>{if(SB.state!=='play')return;SB.state='result';SB.bgm(false);SB.sfx('clear');const t=SB.elapsed,rank=SB.rankFor(t,SB.world),k=String(SB.currentStage),old=save.best[k],isBest=!old||t<old;save.best[k]=isBest?t:old;if(isBest)save.ghosts[k]=SB.ghostFrames.slice();save.stars[k]=Math.max(save.stars[k]||0,SB.player.stars);save.unlocked=Math.max(save.unlocked,Math.min(5,SB.currentStage+2));persist();ui.overlay.classList.remove('hidden');ui.title.textContent='STAGE CLEAR!';ui.text.textContent=SB.world.name;ui.result.classList.remove('hidden');ui.result.innerHTML=`<div class="rank">${rank}</div><div>TIME<br><b>${t.toFixed(2)}s</b>${isBest?'<br>NEW RECORD!':''}</div><div>STAR<br><b>${SB.player.stars}/3</b></div><div>NO DAMAGE<br><b>${SB.runDamage?'NO':'YES'}</b></div>`;ui.menu.innerHTML=`<button id="nextNow">${SB.currentStage<4?'NEXT STAGE':'TITLE'}</button><button id="retryNow" class="secondary">RETRY</button>`;el('nextNow').onclick=()=>SB.currentStage<4?SB.startStage(SB.currentStage+1):SB.showTitle();el('retryNow').onclick=()=>SB.startStage(SB.currentStage);};
SB.showTitle=()=>{SB.state='title';SB.bgm(false);ui.overlay.classList.remove('hidden');ui.title.textContent='Skybound Sprint';ui.text.textContent='走って、跳んで、壁を蹴って、5つのステージを駆け抜けよう。';ui.result.classList.add('hidden');ui.select.classList.add('hidden');ui.menu.innerHTML='<button id="playNow">PLAY</button><button id="selectNow" class="secondary">STAGE SELECT</button><button id="ghostNow" class="secondary">GHOST: '+(save.ghostOn?'ON':'OFF')+'</button>';el('playNow').onclick=()=>SB.startStage(0);el('selectNow').onclick=SB.showStageSelect;el('ghostNow').onclick=()=>{save.ghostOn=!save.ghostOn;persist();SB.showTitle();};};
SB.showStageSelect=()=>{ui.select.innerHTML='';for(let i=0;i<5;i++){const b=document.createElement('button');b.className='stage-card'+(i>=save.unlocked?' locked':'');const best=save.best[i]?save.best[i].toFixed(2)+'s':'--';b.innerHTML=`<b>${i+1}. ${D.stages[i].name}</b><small>BEST ${best} / ★ ${save.stars[i]||0}/3</small>`;b.disabled=i>=save.unlocked;b.onclick=()=>SB.startStage(i);ui.select.appendChild(b);}ui.select.classList.remove('hidden');};
SB.togglePause=()=>{if(SB.state==='play'){SB.state='pause';ui.overlay.classList.remove('hidden');ui.title.textContent='PAUSED';ui.text.textContent='少し休憩。';ui.result.classList.add('hidden');ui.menu.innerHTML='<button id="continueNow">CONTINUE</button><button id="cpNow" class="secondary">RESTART CHECKPOINT</button><button id="stageNow" class="secondary">RESTART STAGE</button><button id="titleNow" class="secondary">TITLE</button>';el('continueNow').onclick=()=>{SB.state='play';ui.overlay.classList.add('hidden');SB.bgm(true);};el('cpNow').onclick=()=>{SB.state='play';ui.overlay.classList.add('hidden');SB.respawn();SB.bgm(true);};el('stageNow').onclick=()=>SB.startStage(SB.currentStage);el('titleNow').onclick=SB.showTitle;SB.bgm(false);}else if(SB.state==='pause'){SB.state='play';ui.overlay.classList.add('hidden');SB.bgm(true);}};

SB.inputDir=()=>Math.sign((SB.input.right||SB.pad.right?1:0)-(SB.input.left||SB.pad.left?1:0));
SB.handleDash=dir=>{const now=performance.now();if(dir!==0&&SB.prevDir===0){if(SB.tapDir===dir&&now-SB.tapTime<260){SB.player.dashUntil=now+430;SB.player.face=dir;SB.shake=4;SB.burst(SB.player.x+SB.player.w/2,SB.player.y+SB.player.h*.7,7,'#dff8ff');SB.sfx('jump',.18);SB.tapDir=0;SB.tapTime=0;}else{SB.tapDir=dir;SB.tapTime=now;}}SB.prevDir=dir;};
SB.dashing=()=>performance.now()<SB.player.dashUntil;
SB.rect=(a,b)=>a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y;
SB.dist=(p,c)=>Math.hypot(p.x+p.w/2-c.x,p.y+p.h/2-c.y);
SB.solids=()=>SB.world.platforms.filter(p=>p.active);
SB.burst=(x,y,n,color)=>{for(let i=0;i<n;i++)SB.particles.push({x,y,vx:(Math.random()-.5)*320,vy:(Math.random()-.9)*300,life:.45+Math.random()*.25,color,size:3+Math.random()*5});if(SB.particles.length>150)SB.particles.splice(0,SB.particles.length-150);};
SB.updatePlatforms=(dt,t)=>{for(const p of SB.world.platforms){if(p.type==='moving'){const q=Math.sin(t*p.speed);if(p.axis==='x')p.x=p.baseX+q*p.range;else p.y=p.baseY+q*p.range;}if(p.type==='crumble'&&p.timer>0){p.timer-=dt;if(p.timer<=0){p.active=false;setTimeout(()=>{p.active=true;p.timer=0;},1400);}}}};
SB.updateEnemies=dt=>{for(const e of SB.world.enemies){if(!e.alive)continue;e.phase+=dt*2.5;if(e.type==='walker'||e.type==='bounce'){e.x+=e.dir*e.speed*dt;if(e.x<e.min||e.x>e.max)e.dir*=-1;if(e.type==='bounce')e.y+=Math.sin(e.phase)*.6;}}};
SB.collideX=prevX=>{const p=SB.player;p.wallDir=0;for(const q of SB.solids()){if(SB.rect(p,q)){if(p.vx>0&&prevX+p.w<=q.x+8){p.x=q.x-p.w;p.vx=0;p.wallDir=1;}else if(p.vx<0&&prevX>=q.x+q.w-8){p.x=q.x+q.w;p.vx=0;p.wallDir=-1;}}}if(p.wallDir)p.wallGrace=.12;};
SB.collideY=prevY=>{const p=SB.player;let landed=false;for(const q of SB.solids()){if(!SB.rect(p,q))continue;if(p.vy>=0&&prevY+p.h<=q.y+10){p.y=q.y-p.h;p.vy=0;landed=true;if(q.type==='crumble'&&!q.timer)q.timer=.35;}else if(p.vy<0&&prevY>=q.y+q.h-8){p.y=q.y+q.h;p.vy=0;}}if(landed&&!p.onGround){SB.sfx('land',.18);SB.burst(p.x+p.w/2,p.y+p.h,5,'#fff');}p.onGround=landed;if(landed)p.coyote=.12;};
SB.updateCamera=dt=>{const p=SB.player,look=p.face*(SB.dashing()?210:120),tx=Math.max(0,Math.min(SB.world.width-W,p.x-W*.38+look));SB.cameraX+=(tx-SB.cameraX)*Math.min(1,dt*4.5);if(SB.world.vertical){const ty=Math.max(0,Math.min(SB.world.height-H,p.y-H*.58-100));SB.cameraY+=(ty-SB.cameraY)*Math.min(1,dt*4.8);}else SB.cameraY=0;};
SB.updateParticles=dt=>{for(const p of SB.particles){p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=650*dt;}SB.particles=SB.particles.filter(p=>p.life>0);};
SB.update=dt=>{if(SB.state!=='play')return;dt=Math.min(dt,.033);SB.elapsed=(performance.now()-SB.stageStart)/1000;SB.updatePlatforms(dt,performance.now()/1000);SB.updateEnemies(dt);const p=SB.player,dir=SB.inputDir(),jp=SB.input.jump||SB.pad.jump;SB.handleDash(dir);if(jp&&!SB.prevJump)p.jumpBuffer=.14;SB.prevJump=jp;p.jumpBuffer=Math.max(0,p.jumpBuffer-dt);p.coyote=Math.max(0,p.coyote-dt);p.wallGrace=Math.max(0,p.wallGrace-dt);p.wallLock=Math.max(0,p.wallLock-dt);p.invuln=Math.max(0,p.invuln-dt);if(p.wallDir)p.wallGrace=.12;const target=dir*(SB.dashing()?730:420);if(p.wallLock<=0)p.vx+=(target-p.vx)*Math.min(1,dt*(p.onGround?13:8));if(dir===0&&p.onGround)p.vx*=Math.pow(.0003,dt);p.vy+=2350*dt;if(p.jumpBuffer>0){if(p.coyote>0){p.vy=-860;p.coyote=0;p.jumpBuffer=0;p.jumpHeld=true;SB.sfx('jump');SB.burst(p.x+p.w/2,p.y+p.h,5,'#fff');}else if(p.wallGrace>0){const kick=-p.wallDir||-p.face;p.vx=kick*540;p.vy=-800;p.face=kick;p.wallGrace=0;p.jumpBuffer=0;p.wallLock=.13;SB.shake=3;SB.burst(p.x+(kick>0?0:p.w),p.y+p.h*.55,7,'#fff');SB.sfx('jump');}}if(!jp&&p.jumpHeld&&p.vy<0){p.vy*=.52;p.jumpHeld=false;}const px=p.x;p.x+=p.vx*dt;SB.collideX(px);const py=p.y;p.y+=p.vy*dt;p.onGround=false;SB.collideY(py);p.x=Math.max(0,Math.min(SB.world.width-p.w,p.x));if(p.y>SB.world.height+180)SB.hurt();for(const h of SB.world.hazards)if(SB.rect(p,h))SB.hurt();for(const c of SB.world.coins)if(!c.taken&&SB.dist(p,c)<42){c.taken=true;p.coins++;SB.sfx('coin');SB.burst(c.x,c.y,7,'#ffd43b');}for(const s of SB.world.stars)if(!s.taken&&SB.dist(p,s)<50){s.taken=true;p.stars++;SB.sfx('coin',.75);SB.shake=5;SB.burst(s.x,s.y,18,'#fff3bf');}for(const cp of SB.world.checkpoints)if(!cp.active&&Math.abs(p.x-cp.x)<55&&Math.abs(p.y-cp.y)<100){SB.world.checkpoints.forEach(x=>x.active=false);cp.active=true;SB.checkpoint={x:cp.x,y:cp.y-70};SB.sfx('coin',.35);}for(const e of SB.world.enemies){if(!e.alive||!SB.rect(p,e))continue;const stomp=p.vy>120&&p.y+p.h-12<e.y+14;if(stomp){p.vy=e.type==='bounce'?-1020:-560;e.alive=false;SB.sfx('stomp');SB.shake=4;SB.burst(e.x+22,e.y+20,10,'#fff');}else SB.hurt();}const g={x:SB.world.goal[0],y:SB.world.goal[1],w:SB.world.goal[2],h:SB.world.goal[3]};if(SB.rect(p,g))SB.finishStage();SB.ghostClock+=dt;if(SB.ghostClock>.075){SB.ghostClock=0;SB.ghostFrames.push([SB.elapsed,p.x,p.y,p.face]);if(SB.ghostFrames.length>2400)SB.ghostFrames.shift();}p.anim+=Math.abs(p.vx)*dt*.024;SB.updateCamera(dt);SB.updateParticles(dt);SB.flash=Math.max(0,SB.flash-dt);SB.shake*=Math.pow(.03,dt);SB.syncHud();};
SB.syncHud=()=>{ui.hearts.textContent='♥'.repeat(Math.max(0,SB.hearts))+'♡'.repeat(Math.max(0,3-SB.hearts));ui.stage.textContent=`STAGE ${SB.currentStage+1}/5`;ui.stars.textContent=`★ ${SB.player.stars}/3`;ui.coins.textContent=`COIN ${SB.player.coins}`;ui.time.textContent=`TIME ${SB.elapsed.toFixed(1)}`;ui.status.textContent=SB.world?SB.world.name:'READY';};
})();