(() => {
'use strict';
const SB=window.SB,{ctx,W,H}=SB;
const visible=o=>o.x+(o.w||0)>SB.cameraX-120&&o.x<SB.cameraX+W+120&&o.y+(o.h||0)>SB.cameraY-120&&o.y<SB.cameraY+H+120;
function starPath(cx,cy,spikes,outer,inner){let rot=Math.PI*1.5,step=Math.PI/spikes;ctx.beginPath();ctx.moveTo(cx,cy-outer);for(let i=0;i<spikes;i++){ctx.lineTo(cx+Math.cos(rot)*outer,cy+Math.sin(rot)*outer);rot+=step;ctx.lineTo(cx+Math.cos(rot)*inner,cy+Math.sin(rot)*inner);rot+=step;}ctx.closePath();}
function bg(){const g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,SB.currentStage===4?'#183153':'#75d6f2');g.addColorStop(1,SB.currentStage===4?'#c3e7f2':'#effcff');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.fillStyle='#ffffffb8';for(let i=0;i<10;i++){const x=((i*370-SB.cameraX*.12)%1700+1700)%1700-120,y=70+(i%4)*95;ctx.beginPath();ctx.arc(x,y,25+(i%3)*8,0,Math.PI*2);ctx.arc(x+30,y+4,20,0,Math.PI*2);ctx.fill();}}
function platform(p){const img=SB.art.tile1;if(img?.complete&&img.naturalWidth){for(let x=p.x;x<p.x+p.w;x+=64){const dw=Math.min(64,p.x+p.w-x);ctx.drawImage(img,0,0,img.naturalWidth,img.naturalHeight,x,p.y,dw,Math.min(64,p.h));}}else{ctx.fillStyle=p.type==='crumble'?'#b08968':'#8d6e63';ctx.fillRect(p.x,p.y,p.w,p.h);ctx.fillStyle='#69c34a';ctx.fillRect(p.x,p.y,p.w,10);}if(p.type==='moving'){ctx.strokeStyle='#e7f5ff';ctx.lineWidth=3;ctx.strokeRect(p.x,p.y,p.w,p.h);}if(p.type==='crumble'&&p.timer>0){ctx.strokeStyle='#fff3bf';ctx.lineWidth=3;ctx.strokeRect(p.x,p.y,p.w,p.h);}}
function hazard(h){ctx.fillStyle='#d9480f';for(let x=h.x;x<h.x+h.w;x+=28){ctx.beginPath();ctx.moveTo(x,h.y+h.h);ctx.lineTo(x+14,h.y);ctx.lineTo(x+28,h.y+h.h);ctx.fill();}}
function coin(c,isStar){ctx.save();ctx.translate(c.x,c.y);const q=1+Math.sin(performance.now()/130)*.07;ctx.scale(q,q);if(isStar){ctx.fillStyle='#ffd43b';starPath(0,0,5,22,10);ctx.fill();ctx.strokeStyle='#fff3bf';ctx.lineWidth=4;ctx.stroke();}else if(SB.art.item?.complete&&SB.art.item.naturalWidth)ctx.drawImage(SB.art.item,-24,-24,48,48);else{ctx.fillStyle='#ffd43b';ctx.beginPath();ctx.arc(0,0,13,0,Math.PI*2);ctx.fill();}ctx.restore();}
function checkpoint(cp){ctx.strokeStyle=cp.active?'#51cf66':'#fff';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(cp.x,cp.y);ctx.lineTo(cp.x,cp.y-90);ctx.stroke();ctx.fillStyle=cp.active?'#51cf66':'#74c0fc';ctx.fillRect(cp.x,cp.y-90,45,24);}
function enemy(e){ctx.save();ctx.translate(e.x,e.y);ctx.fillStyle=e.type==='bounce'?'#845ef7':'#7048e8';ctx.beginPath();if(ctx.roundRect)ctx.roundRect(0,6,e.w,e.h-6,13);else ctx.rect(0,6,e.w,e.h-6);ctx.fill();ctx.fillStyle='#fff';ctx.fillRect(8,17,8,8);ctx.fillRect(28,17,8,8);ctx.restore();}
function goal(){const [x,y,,h]=SB.world.goal;ctx.strokeStyle='#495057';ctx.lineWidth=6;ctx.beginPath();ctx.moveTo(x,y+h);ctx.lineTo(x,y);ctx.stroke();ctx.fillStyle='#ff6b6b';ctx.fillRect(x,y,62,34);}
function ghost(){if(!SB.save.ghostOn)return;const data=SB.save.ghosts[SB.currentStage];if(!data?.length)return;let f=data[0];for(let i=1;i<data.length;i++){if(data[i][0]>=SB.elapsed){f=data[i-1]||data[i];break;}}ctx.save();ctx.globalAlpha=.2;ctx.fillStyle='#fff';ctx.fillRect(f[1],f[2],SB.player.w,SB.player.h);ctx.restore();}
function player(){const p=SB.player;if(p.invuln>0&&Math.floor(performance.now()/80)%2===0)return;let img=SB.art.idle;if(!p.onGround)img=SB.art.jump;else if(Math.abs(p.vx)>60)img=Math.floor(p.anim)%2?SB.art.walk1:SB.art.walk2;ctx.save();ctx.translate(p.x+p.w/2,p.y+p.h/2);ctx.scale(p.face<0?-1:1,1);if(SB.dashing()){ctx.globalAlpha=.18;for(let i=1;i<=3;i++){ctx.fillStyle='#dff8ff';ctx.fillRect(-p.w/2-p.face*i*16,-p.h/2,p.w,p.h);}ctx.globalAlpha=1;}if(img?.complete&&img.naturalWidth)ctx.drawImage(img,-p.w/2-9,-p.h/2-5,p.w+18,p.h+10);else{ctx.fillStyle='#ff8fab';ctx.fillRect(-p.w/2,-p.h/2,p.w,p.h);}ctx.restore();}
SB.draw=()=>{ctx.save();ctx.translate((Math.random()-.5)*SB.shake,(Math.random()-.5)*SB.shake);bg();if(SB.world){ctx.save();ctx.translate(-SB.cameraX,-SB.cameraY);ghost();for(const p of SB.world.platforms)if(p.active&&visible(p))platform(p);for(const h of SB.world.hazards)if(visible(h))hazard(h);for(const c of SB.world.coins)if(!c.taken)coin(c,false);for(const s of SB.world.stars)if(!s.taken)coin(s,true);for(const cp of SB.world.checkpoints)checkpoint(cp);for(const e of SB.world.enemies)if(e.alive&&visible(e))enemy(e);goal();player();for(const p of SB.particles){ctx.globalAlpha=Math.max(0,p.life/.7);ctx.fillStyle=p.color;ctx.fillRect(p.x,p.y,p.size,p.size);}ctx.globalAlpha=1;ctx.restore();}if(SB.flash>0){ctx.fillStyle=`rgba(255,255,255,${SB.flash})`;ctx.fillRect(0,0,W,H);}ctx.restore();};
})();